### ISSUE TITLE
Does it need a Jar file to be use ?

### ISSUE THREAD

**Issue by piellick** [tobiasstadler/apm-wildfly-remote-ejb-plugin#5]
Hi Tobias,
great works !

For non Java devs, does we need a build environnement like eclips ?

It would be possible to have a jar file ?

Are you using Apm java plugin directory ?
https://www.elastic.co/guide/en/apm/agent/java/master/config-core.html#config-plugins-dir

thanks .

**Comment by tobiasstadler** [comment]
Hi @piellick 

Sorry, I had a bug in my release script which prevented the jar from being published. Now you can find the jar here: https://github.com/tobiasstadler/apm-wildfly-remote-ejb-plugin/releases/tag/1.1

Yes, you need to put `apm-wildfly-remote-ejb-plugin-1.1.jar` inside the `plugins_dir` directory. Also you need to remove `(?-i)org.jboss.as.*` from `classes_excluded_from_instrumentation_default` setting (at least until elastic/apm-agent-java#1920 is merged) or the server side instrumentation will not work, e.g. as in my integration test:  https://github.com/tobiasstadler/apm-wildfly-remote-ejb-plugin/blob/710eaaf264d311b60bd44b1ed23a4538b24b1725/integration-test/src/test/java/co/elastic/apm/agent/wildfly_remote_ejb/RemoteEJBIT.java#L97 

I hope this helps.

**Comment by piellick** [comment]
Thanks a lot, i'll try.
